In [3]:
import pandas as pd

df = pd.read_csv(r'data/teg-all-data-long.csv')
#print(df)

# List the column names
columns = df.columns

# # Display the column names
# print("Column Names:")
# print(columns)

# # Convert to a list if needed
# columns_list = list(columns)
# print("\nColumn Names as a List:")
# print(columns_list)

print(df.head(200).to_string())

        TEG  Round  Hole  PAR  SI  Pl  Sc  HC  Hcstrokes  GrossVP  Net  NetVP  Stableford  TEGNum
0    TEG 10      1     1    4  14  DM   4  17          1        0    3     -1           3      10
1    TEG 10      1     2    3  16  DM   4  17          1        1    3      0           2      10
2    TEG 10      1     3    5   8  DM   6  17          1        1    5      0           2      10
3    TEG 10      1     4    3   6  DM   4  17          1        1    3      0           2      10
4    TEG 10      1     5    4  12  DM   5  17          1        1    4      0           2      10
5    TEG 10      1     6    3   4  DM   3  17          1        0    2     -1           3      10
6    TEG 10      1     7    4  10  DM   4  17          1        0    3     -1           3      10
7    TEG 10      1     8    5   2  DM   5  17          1        0    4     -1           3      10
8    TEG 10      1     9    4  18  DM   5  17          0        1    5      1           1      10
9    TEG 10      1    10    4   3  DM   4  17          1        0    3     -1           3      10
10   TEG 10      1    11    3  13  DM   4  17          1        1    3      0           2      10
11   TEG 10      1    12    4  11  DM   4  17          1        0    3     -1           3      10
12   TEG 10      1    13    5  15  DM   4  17          1       -1    3     -2           4      10
13   TEG 10      1    14    3   7  DM   2  17          1       -1    1     -2           4      10
14   TEG 10      1    15    4   1  DM   5  17          1        1    4      0           2      10
15   TEG 10      1    16    5   9  DM   4  17          1       -1    3     -2           4      10
16   TEG 10      1    17    4  17  DM   4  17          1        0    3     -1           3      10
17   TEG 10      1    18    4   5  DM   4  17          1        0    3     -1           3      10
18   TEG 10      2     1    4   5  DM   4  17          1        0    3     -1           3      10
19   TEG 10      2     2    5   7  DM   6  17          1        1    5      0           2      10
20   TEG 10      2     3    3  15  DM   5  17          1        2    4      1           1      10
21   TEG 10      2     4    5   1  DM   5  17          1        0    4     -1           3      10
22   TEG 10      2     5    3  11  DM   3  17          1        0    2     -1           3      10
23   TEG 10      2     6    4   9  DM   4  17          1        0    3     -1           3      10
24   TEG 10      2     7    4  13  DM   4  17          1        0    3     -1           3      10
25   TEG 10      2     8    3  17  DM   3  17          1        0    2     -1           3      10
26   TEG 10      2     9    5   3  DM   7  17          1        2    6      1           1      10
27   TEG 10      2    10    4   4  DM   4  17          1        0    3     -1           3      10
28   TEG 10      2    11    3  14  DM   4  17          1        1    3      0           2      10
29   TEG 10      2    12    4   8  DM   5  17          1        1    4      0           2      10
30   TEG 10      2    13    5  10  DM   5  17          1        0    4     -1           3      10
31   TEG 10      2    14    4  18  DM   6  17          0        2    6      2           0      10
32   TEG 10      2    15    4  12  DM   4  17          1        0    3     -1           3      10
33   TEG 10      2    16    3  16  DM   4  17          1        1    3      0           2      10
34   TEG 10      2    17    5   6  DM   6  17          1        1    5      0           2      10
35   TEG 10      2    18    4   2  DM   4  17          1        0    3     -1           3      10
36   TEG 10      3     1    4   3  DM   5  17          1        1    4      0           2      10
37   TEG 10      3     2    3  13  DM   4  17          1        1    3      0           2      10
38   TEG 10      3     3    4   7  DM   5  17          1        1    4      0           2      10
39   TEG 10      3     4    5   9  DM   8  17          1        3    7      2           0      10
40   TEG 10      3     5    4  17  DM   4  17          1        0    3     -1           3      10
41   TEG 10      3     6    4  11  DM   5  17          1        1    4      0           2      10
42   TEG 10      3     7    3  15  DM   3  17          1        0    2     -1           3      10
43   TEG 10      3     8    5   5  DM   7  17          1        2    6      1           1      10
44   TEG 10      3     9    4   1  DM   7  17          1        3    6      2           0      10
45   TEG 10      3    10    4   8  DM   5  17          1        1    4      0           2      10
46   TEG 10      3    11    4   2  DM   7  17          1        3    6      2           0      10
47   TEG 10      3    12    3  18  DM   3  17          0        0    3      0           2      10
48   TEG 10      3    13    5   4  DM   8  17          1        3    7      2           0      10
49   TEG 10      3    14    3  14  DM   5  17          1        2    4      1           1      10
50   TEG 10      3    15    5  10  DM   4  17          1       -1    3     -2           4      10
51   TEG 10      3    16    3  16  DM   3  17          1        0    2     -1           3      10
52   TEG 10      3    17    5  12  DM   4  17          1       -1    3     -2           4      10
53   TEG 10      3    18    4   6  DM   8  17          1        4    7      3           0      10
54   TEG 10      4     1    4  14  DM   4  17          1        0    3     -1           3      10
55   TEG 10      4     2    3  16  DM   3  17          1        0    2     -1           3      10
56   TEG 10      4     3    5   8  DM   6  17          1        1    5      0           2      10
57   TEG 10      4     4    3   6  DM   4  17          1        1    3      0           2      10
58   TEG 10      4     5    4  12  DM   5  17          1        1    4      0           2      10
59   TEG 10      4     6    3   4  DM   4  17          1        1    3      0           2      10
60   TEG 10      4     7    4  10  DM   5  17          1        1    4      0           2      10
61   TEG 10      4     8    5   2  DM   6  17          1        1    5      0           2      10
62   TEG 10      4     9    4  18  DM   4  17          0        0    4      0           2      10
63   TEG 10      4    10    4   3  DM   6  17          1        2    5      1           1      10
64   TEG 10      4    11    3  13  DM   4  17          1        1    3      0           2      10
65   TEG 10      4    12    4  11  DM   5  17          1        1    4      0           2      10
66   TEG 10      4    13    5  15  DM   5  17          1        0    4     -1           3      10
67   TEG 10      4    14    3   7  DM   3  17          1        0    2     -1           3      10
68   TEG 10      4    15    4   1  DM   6  17          1        2    5      1           1      10
69   TEG 10      4    16    5   9  DM   4  17          1       -1    3     -2           4      10
70   TEG 10      4    17    4  17  DM   6  17          1        2    5      1           1      10
71   TEG 10      4    18    4   5  DM   4  17          1        0    3     -1           3      10
72   TEG 11      1     1    4   3  DM   4  13          1        0    3     -1           3      11
73   TEG 11      1     2    4   5  DM   5  13          1        1    4      0           2      11
74   TEG 11      1     3    5  13  DM   6  13          1        1    5      0           2      11
75   TEG 11      1     4    4   9  DM   6  13          1        2    5      1           1      11
76   TEG 11      1     5    3   7  DM   4  13          1        1    3      0           2      11
77   TEG 11      1     6    4  11  DM   4  13          1        0    3     -1           3      11
78   TEG 11      1     7    5  17  DM   7  13          0        2    7      2           0      11
79   TEG 11      1     8    3  15  DM   3  13          0        0    3      0           2      11
80   TEG 11      1     9    4   1  DM   6  13          1        2    5      1           1      11
81   TEG 11      1    10    4  12  DM   5  13          1        1    4      0           2      11
82   TEG 11      1    11    3  16  DM   4  13          0        1    4      1           1      11
83   TEG 11      1    12    5  14  DM   6  13          0        1    6      1           1      11
84   TEG 11      1    13    4   6  DM   5  13          1        1    4      0           2      11
85   TEG 11      1    14    4   4  DM   6  13          1        2    5      1           1      11
86   TEG 11      1    15    5  18  DM   6  13          0        1    6      1           1      11
87   TEG 11      1    16    3  10  DM   4  13          1        1    3      0           2      11
88   TEG 11      1    17    4   8  DM   5  13          1        1    4      0           2      11
89   TEG 11      1    18    4   2  DM   6  13          1        2    5      1           1      11
90   TEG 11      2     1    4  14  DM   4  13          0        0    4      0           2      11
91   TEG 11      2     2    3  18  DM   2  13          0       -1    2     -1           3      11
92   TEG 11      2     3    4   6  DM   6  13          1        2    5      1           1      11
93   TEG 11      2     4    4   2  DM   5  13          1        1    4      0           2      11
94   TEG 11      2     5    5  16  DM   7  13          0        2    7      2           0      11
95   TEG 11      2     6    4  12  DM   6  13          1        2    5      1           1      11
96   TEG 11      2     7    5   8  DM   6  13          1        1    5      0           2      11
97   TEG 11      2     8    3   4  DM   3  13          1        0    2     -1           3      11
98   TEG 11      2     9    4  10  DM   4  13          1        0    3     -1           3      11
99   TEG 11      2    10    5   9  DM   4  13          1       -1    3     -2           4      11
100  TEG 11      2    11    3   7  DM   4  13          1        1    3      0           2      11
101  TEG 11      2    12    4  11  DM   4  13          1        0    3     -1           3      11
102  TEG 11      2    13    4   1  DM   6  13          1        2    5      1           1      11
103  TEG 11      2    14    3  13  DM   5  13          1        2    4      1           1      11
104  TEG 11      2    15    5   5  DM   6  13          1        1    5      0           2      11
105  TEG 11      2    16    3  17  DM   3  13          0        0    3      0           2      11
106  TEG 11      2    17    4   3  DM   5  13          1        1    4      0           2      11
107  TEG 11      2    18    5  15  DM   5  13          0        0    5      0           2      11
108  TEG 11      3     1    4   3  DM   5  13          1        1    4      0           2      11
109  TEG 11      3     2    3  17  DM   3  13          0        0    3      0           2      11
110  TEG 11      3     3    4  15  DM   4  13          0        0    4      0           2      11
111  TEG 11      3     4    5  13  DM   6  13          1        1    5      0           2      11
112  TEG 11      3     5    4   5  DM   4  13          1        0    3     -1           3      11
113  TEG 11      3     6    3  11  DM   7  13          1        4    6      3           0      11
114  TEG 11      3     7    4   9  DM   4  13          1        0    3     -1           3      11
115  TEG 11      3     8    4   1  DM   5  13          1        1    4      0           2      11
116  TEG 11      3     9    5   7  DM   6  13          1        1    5      0           2      11
117  TEG 11      3    10    5   8  DM   5  13          1        0    4     -1           3      11
118  TEG 11      3    11    4   4  DM   7  13          1        3    6      2           0      11
119  TEG 11      3    12    3  18  DM   4  13          0        1    4      1           1      11
120  TEG 11      3    13    4  12  DM   7  13          1        3    6      2           0      11
121  TEG 11      3    14    4  14  DM   5  13          0        1    5      1           1      11
122  TEG 11      3    15    3  10  DM   5  13          1        2    4      1           1      11
123  TEG 11      3    16    4   6  DM   5  13          1        1    4      0           2      11
124  TEG 11      3    17    4   2  DM   6  13          1        2    5      1           1      11
125  TEG 11      3    18    5  16  DM   5  13          0        0    5      0           2      11
126  TEG 11      4     1    4   3  DM   4  13          1        0    3     -1           3      11
127  TEG 11      4     2    4   5  DM   4  13          1        0    3     -1           3      11
128  TEG 11      4     3    5  13  DM   5  13          1        0    4     -1           3      11
129  TEG 11      4     4    4   9  DM   5  13          1        1    4      0           2      11
130  TEG 11      4     5    3   7  DM   4  13          1        1    3      0           2      11
131  TEG 11      4     6    4  11  DM   6  13          1        2    5      1           1      11
132  TEG 11      4     7    5  17  DM   6  13          0        1    6      1           1      11
133  TEG 11      4     8    3  15  DM   3  13          0        0    3      0           2      11
134  TEG 11      4     9    4   1  DM   5  13          1        1    4      0           2      11
135  TEG 11      4    10    4  12  DM   6  13          1        2    5      1           1      11
136  TEG 11      4    11    3  16  DM   3  13          0        0    3      0           2      11
137  TEG 11      4    12    5  14  DM   6  13          0        1    6      1           1      11
138  TEG 11      4    13    4   6  DM   6  13          1        2    5      1           1      11
139  TEG 11      4    14    4   4  DM   5  13          1        1    4      0           2      11
140  TEG 11      4    15    5  18  DM   8  13          0        3    8      3           0      11
141  TEG 11      4    16    3  10  DM   5  13          1        2    4      1           1      11
142  TEG 11      4    17    4   8  DM   6  13          1        2    5      1           1      11
143  TEG 11      4    18    4   2  DM   4  13          1        0    3     -1           3      11
144  TEG 12      1     1    4  14  DM   5  16          1        1    4      0           2      12
145  TEG 12      1     2    3  18  DM   3  16          0        0    3      0           2      12
146  TEG 12      1     3    4   6  DM   4  16          1        0    3     -1           3      12
147  TEG 12      1     4    4   2  DM   7  16          1        3    6      2           0      12
148  TEG 12      1     5    5  16  DM   6  16          1        1    5      0           2      12
149  TEG 12      1     6    4  12  DM   4  16          1        0    3     -1           3      12
150  TEG 12      1     7    5   8  DM   6  16          1        1    5      0           2      12
151  TEG 12      1     8    3   4  DM   4  16          1        1    3      0           2      12
152  TEG 12      1     9    4  10  DM   5  16          1        1    4      0           2      12
153  TEG 12      1    10    5   9  DM   7  16          1        2    6      1           1      12
154  TEG 12      1    11    3   7  DM   5  16          1        2    4      1           1      12
155  TEG 12      1    12    4  11  DM   6  16          1        2    5      1           1      12
156  TEG 12      1    13    4   1  DM   5  16          1        1    4      0           2      12
157  TEG 12      1    14    3  13  DM   3  16          1        0    2     -1           3      12
158  TEG 12      1    15    5   5  DM   6  16          1        1    5      0           2      12
159  TEG 12      1    16    3  17  DM   3  16          0        0    3      0           2      12
160  TEG 12      1    17    4   3  DM   5  16          1        1    4      0           2      12
161  TEG 12      1    18    5  15  DM   5  16          1        0    4     -1           3      12
162  TEG 12      2     1    4  14  DM   4  16          1        0    3     -1           3      12
163  TEG 12      2     2    3  18  DM   5  16          0        2    5      2           0      12
164  TEG 12      2     3    4   6  DM   4  16          1        0    3     -1           3      12
165  TEG 12      2     4    4   2  DM   5  16          1        1    4      0           2      12
166  TEG 12      2     5    5  16  DM   5  16          1        0    4     -1           3      12
167  TEG 12      2     6    4  12  DM   4  16          1        0    3     -1           3      12
168  TEG 12      2     7    5   8  DM   5  16          1        0    4     -1           3      12
169  TEG 12      2     8    3   4  DM   3  16          1        0    2     -1           3      12
170  TEG 12      2     9    4  10  DM   7  16          1        3    6      2           0      12
171  TEG 12      2    10    5   9  DM   5  16          1        0    4     -1           3      12
172  TEG 12      2    11    3   7  DM   4  16          1        1    3      0           2      12
173  TEG 12      2    12    4  11  DM   4  16          1        0    3     -1           3      12
174  TEG 12      2    13    4   1  DM   6  16          1        2    5      1           1      12
175  TEG 12      2    14    3  13  DM   3  16          1        0    2     -1           3      12
176  TEG 12      2    15    5   5  DM   6  16          1        1    5      0           2      12
177  TEG 12      2    16    3  17  DM   4  16          0        1    4      1           1      12
178  TEG 12      2    17    4   3  DM   4  16          1        0    3     -1           3      12
179  TEG 12      2    18    5  15  DM   6  16          1        1    5      0           2      12
180  TEG 12      3     1    4   3  DM   6  16          1        2    5      1           1      12
181  TEG 12      3     2    4   5  DM   7  16          1        3    6      2           0      12
182  TEG 12      3     3    5  13  DM   6  16          1        1    5      0           2      12
183  TEG 12      3     4    4   9  DM   6  16          1        2    5      1           1      12
184  TEG 12      3     5    3   7  DM   3  16          1        0    2     -1           3      12
185  TEG 12      3     6    4  11  DM   6  16          1        2    5      1           1      12
186  TEG 12      3     7    5  17  DM   5  16          0        0    5      0           2      12
187  TEG 12      3     8    3  15  DM   4  16          1        1    3      0           2      12
188  TEG 12      3     9    4   1  DM   6  16          1        2    5      1           1      12
189  TEG 12      3    10    4  12  DM   5  16          1        1    4      0           2      12
190  TEG 12      3    11    3  16  DM   3  16          1        0    2     -1           3      12
191  TEG 12      3    12    5  14  DM   7  16          1        2    6      1           1      12
192  TEG 12      3    13    4   6  DM   5  16          1        1    4      0           2      12
193  TEG 12      3    14    4   4  DM   5  16          1        1    4      0           2      12
194  TEG 12      3    15    5  18  DM   5  16          0        0    5      0           2      12
195  TEG 12      3    16    3  10  DM   5  16          1        2    4      1           1      12
196  TEG 12      3    17    4   8  DM   5  16          1        1    4      0           2      12
197  TEG 12      3    18    4   2  DM   5  16          1        1    4      0           2      12
198  TEG 12      4     1    4   3  DM   5  16          1        1    4      0           2      12
199  TEG 12      4     2    4   5  DM   5  16          1        1    4      0           2      12

In [84]:
# Group by 'TEG' and 'Pl', and sum the 'Sc' column
summary_table = df.groupby(['TEG', 'Pl'])['Sc'].sum().reset_index()
# summary_table2 = df.groupby(['TEG', 'Pl'])['Sc'].sum()

# Display the summary table
print(summary_table)

       TEG  Pl   Sc
0   TEG 10  AB  376
1   TEG 10  DM  337
2   TEG 10  GW  362
3   TEG 10  JB  349
4   TEG 10  JP  418
5   TEG 10  SN  411
6   TEG 11  AB  394
7   TEG 11  DM  361
8   TEG 11  GW  387
9   TEG 11  JB  358
10  TEG 11  JP  411
11  TEG 12  AB  392
12  TEG 12  DM  359
13  TEG 12  GW  364
14  TEG 12  JB  351
15  TEG 12  JP  384
16  TEG 12  SN  396
17  TEG 13  AB  390
18  TEG 13  DM  367
19  TEG 13  GW  355
20  TEG 13  JB  337
21  TEG 13  JP  393
22  TEG 14  AB  390
23  TEG 14  DM  367
24  TEG 14  GW  355
25  TEG 14  JB  337
26  TEG 14  JP  393
27  TEG 15  AB  418
28  TEG 15  DM  377
29  TEG 15  GW  347
30  TEG 15  JB  376
31  TEG 15  JP  397
32  TEG 15  SN  412
33  TEG 16  AB  432
34  TEG 16  DM  366
35  TEG 16  GW  350
36  TEG 16  JB  377
37  TEG 16  SN  389
38   TEG 2  DM  279
39   TEG 2  GW  324
40   TEG 2  HM  306
41   TEG 2  JB  310
42   TEG 2  SN  290
43   TEG 3  DM  356
44   TEG 3  GW  411
45   TEG 3  HM  380
46   TEG 3  JB  378
47   TEG 3  SN  368
48   TEG 4  DM  364
49   TEG 4  GW  435
50   TEG 4  HM  390
51   TEG 4  JB  396
52   TEG 4  SN  383
53   TEG 5  DM  357
54   TEG 5  GW  411
55   TEG 5  HM  375
56   TEG 5  JB  369
57   TEG 5  SN  373
58   TEG 6  DM  374
59   TEG 6  GW  417
60   TEG 6  HM  407
61   TEG 6  JB  378
62   TEG 6  SN  386
63   TEG 7  AB  429
64   TEG 7  DM  343
65   TEG 7  GW  394
66   TEG 7  HM  359
67   TEG 7  JB  361
68   TEG 7  SN  358
69   TEG 8  AB  433
70   TEG 8  DM  362
71   TEG 8  GW  392
72   TEG 8  HM  408
73   TEG 8  JB  368
74   TEG 8  SN  422
75   TEG 9  AB  417
76   TEG 9  DM  357
77   TEG 9  GW  405
78   TEG 9  JB  367
79   TEG 9  JP  378
80   TEG 9  SN  415

In [85]:
# Pivot the table to show the sum of Sc for each Pl and TEG
#pivot_table = df.pivot_table(index='TEG', columns='Pl', values='Sc', aggfunc='sum')
pivot_table = df.pivot_table(index=['TEGNum','Round'], columns='Pl', values='Sc', aggfunc='sum')

# Display the pivot table
#print(pivot_table)

pivot_filtered =  pivot_table.loc[2]
#print(pivot_filtered)



pivot_table_styled = pivot_filtered.style.format("{:.0f}", na_rep="-")
pivot_table_styled

In [86]:
pivot_table = df.pivot_table(index='SI', columns='HC', values='Hcstrokes', aggfunc=['mean','min','max']).fillna(0)

pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)
#pd.reset_option('display.max_rows')


#print(pivot_table)
#pivot_table.to_clipboard(index=True)

#print(df)


# column_sums = pivot_table.sum()
# print(column_sums)

In [87]:
from IPython.display import display
display(column_sums)

NameError: name 'column_sums' is not defined

In [26]:
pivot_table = df.pivot_table(index=['TEG','TEGNum'], columns='Pl', values='Stableford', aggfunc=['sum']).fillna(0).sort_values(by='TEGNum')
display(pivot_table)

                 sum
Pl                AB     DM     GW     HM     JB     JP     SN
TEG    TEGNum
TEG 2  2         0.0  103.0   86.0   75.0   98.0    0.0   89.0
TEG 3  3         0.0  147.0  138.0  137.0  164.0    0.0  135.0
TEG 4  4         0.0  137.0  110.0  121.0  134.0    0.0  120.0
TEG 5  5         0.0  136.0  153.0  139.0  156.0    0.0  139.0
TEG 6  6         0.0  135.0  145.0  123.0  142.0    0.0  139.0
TEG 7  7       152.0  170.0  170.0  175.0  164.0    0.0  169.0
TEG 8  8       137.0  126.0  149.0  111.0  131.0    0.0  100.0
TEG 9  9       162.0  148.0  143.0    0.0  146.0  168.0  127.0
TEG 10 10      184.0  162.0  173.0    0.0  157.0  112.0  144.0
TEG 11 11      137.0  125.0  136.0    0.0  143.0  135.0    0.0
TEG 12 12      143.0  139.0  162.0    0.0  145.0  172.0  155.0
TEG 13 13      141.0  135.0  152.0    0.0  158.0  141.0    0.0
TEG 14 14      145.0  143.0  144.0    0.0  146.0  141.0    0.0
TEG 15 15      114.0  125.0  157.0    0.0  131.0  135.0  136.0
TEG 16 16      127.0  141.0  142.0    0.0  130.0    0.0  154.0

In [27]:
pivot_table = df.pivot_table(index=['TEG','TEGNum'], columns='Pl', values='Stableford', aggfunc=['sum']).sort_values(by='TEGNum').reset_index(level='TEGNum', drop=True)
display(pivot_table)

best_stab = pivot_table.max()
display(best_stab)

          sum
Pl         AB     DM     GW     HM     JB     JP     SN
TEG
TEG 2     NaN  103.0   86.0   75.0   98.0    NaN   89.0
TEG 3     NaN  147.0  138.0  137.0  164.0    NaN  135.0
TEG 4     NaN  137.0  110.0  121.0  134.0    NaN  120.0
TEG 5     NaN  136.0  153.0  139.0  156.0    NaN  139.0
TEG 6     NaN  135.0  145.0  123.0  142.0    NaN  139.0
TEG 7   152.0  170.0  170.0  175.0  164.0    NaN  169.0
TEG 8   137.0  126.0  149.0  111.0  131.0    NaN  100.0
TEG 9   162.0  148.0  143.0    NaN  146.0  168.0  127.0
TEG 10  184.0  162.0  173.0    NaN  157.0  112.0  144.0
TEG 11  137.0  125.0  136.0    NaN  143.0  135.0    NaN
TEG 12  143.0  139.0  162.0    NaN  145.0  172.0  155.0
TEG 13  141.0  135.0  152.0    NaN  158.0  141.0    NaN
TEG 14  145.0  143.0  144.0    NaN  146.0  141.0    NaN
TEG 15  114.0  125.0  157.0    NaN  131.0  135.0  136.0
TEG 16  127.0  141.0  142.0    NaN  130.0    NaN  154.0

     Pl
sum  AB    184.0
     DM    170.0
     GW    173.0
     HM    175.0
     JB    164.0
     JP    172.0
     SN    169.0
dtype: float64

In [37]:
gross_by_teg_df = df.groupby(['TEG', 'Pl'], as_index=False)['GrossVP'].sum().sort_values(by='GrossVP', ascending=True)
gross_by_teg_df['Rank'] = gross_by_teg_df['GrossVP'].rank(ascending=True, method='min').astype(int)
gross_by_teg_df = gross_by_teg_df[['Rank','GrossVP','Pl','TEG']]

# display(gross_by_teg_df)
pd.set_option('display.max_rows', None)

print(gross_by_teg_df)

    Rank  GrossVP  Pl     TEG
25     1       50  JB  TEG 14
20     1       50  JB  TEG 13
1      3       51  DM  TEG 10
64     4       53  DM   TEG 7
3      5       63  JB  TEG 10
29     5       63  GW  TEG 15
14     5       63  JB  TEG 12
38     8       66  DM   TEG 2
76     9       67  DM   TEG 9
35    10       68  GW  TEG 16
24    10       68  GW  TEG 14
19    10       68  GW  TEG 13
68    10       68  SN   TEG 7
66    14       69  HM   TEG 7
9     15       70  JB  TEG 11
12    16       71  DM  TEG 12
67    16       71  JB   TEG 7
43    18       72  DM   TEG 3
53    18       72  DM   TEG 5
7     20       73  DM  TEG 11
13    21       76  GW  TEG 12
2     21       76  GW  TEG 10
42    23       77  SN   TEG 2
70    23       77  DM   TEG 8
78    23       77  JB   TEG 9
18    26       80  DM  TEG 13
23    26       80  DM  TEG 14
48    28       81  DM   TEG 4
73    29       83  JB   TEG 8
56    30       84  JB   TEG 5
47    30       84  SN   TEG 3
34    30       84  DM  TEG 16
58    33       85  DM   TEG 6
57    34       88  SN   TEG 5
79    34       88  JP   TEG 9
61    36       89  JB   TEG 6
55    37       90  HM   TEG 5
0     37       90  AB  TEG 10
30    39       92  JB  TEG 15
40    40       93  HM   TEG 2
28    40       93  DM  TEG 15
46    42       94  JB   TEG 3
36    43       95  JB  TEG 16
45    44       96  HM   TEG 3
15    44       96  JP  TEG 12
41    46       97  JB   TEG 2
62    46       97  SN   TEG 6
8     48       99  GW  TEG 11
52    49      100  SN   TEG 4
17    50      103  AB  TEG 13
22    50      103  AB  TEG 14
65    52      104  GW   TEG 7
11    52      104  AB  TEG 12
26    54      106  JP  TEG 14
21    54      106  JP  TEG 13
6     54      106  AB  TEG 11
71    57      107  GW   TEG 8
50    57      107  HM   TEG 4
37    57      107  SN  TEG 16
16    60      108  SN  TEG 12
39    61      111  GW   TEG 2
31    62      113  JP  TEG 15
51    62      113  JB   TEG 4
77    64      115  GW   TEG 9
60    65      118  HM   TEG 6
10    66      123  JP  TEG 11
72    66      123  HM   TEG 8
5     68      125  SN  TEG 10
80    68      125  SN   TEG 9
54    70      126  GW   TEG 5
44    71      127  GW   TEG 3
75    71      127  AB   TEG 9
59    73      128  GW   TEG 6
32    73      128  SN  TEG 15
4     75      132  JP  TEG 10
27    76      134  AB  TEG 15
74    77      137  SN   TEG 8
63    78      139  AB   TEG 7
69    79      148  AB   TEG 8
33    80      150  AB  TEG 16
49    81      152  GW   TEG 4

In [41]:
gross_by_rd_df = df.groupby(['TEG','Round', 'Pl'], as_index=False)['GrossVP'].sum().sort_values(by='GrossVP', ascending=True)
gross_by_rd_df['Rank'] = gross_by_rd_df['GrossVP'].rank(ascending=True, method='min').astype(int)
gross_by_rd_df = gross_by_rd_df[['Rank','GrossVP','Pl','TEG','Round']]

# display(gross_by_teg_df)
pd.set_option('display.max_rows', None)

print(gross_by_rd_df)

     Rank  GrossVP  Pl     TEG  Round
1       1        4  DM  TEG 10      1
81      2        8  JB  TEG 13      3
101     2        8  JB  TEG 14      3
254     4        9  DM   TEG 7      2
258     5       10  SN   TEG 7      2
266     5       10  DM   TEG 7      4
9       5       10  JB  TEG 10      2
122     5       10  GW  TEG 15      3
256     5       10  HM   TEG 7      2
270    10       11  SN   TEG 7      4
212    10       11  DM   TEG 5      2
148    10       11  DM  TEG 16      4
7      10       11  DM  TEG 10      2
216    10       11  SN   TEG 5      2
149    10       11  GW  TEG 16      4
251    10       11  JB   TEG 7      1
32     17       12  JB  TEG 11      2
102    17       12  JP  TEG 14      3
207    17       12  DM   TEG 5      1
47     17       12  JB  TEG 12      1
250    17       12  HM   TEG 7      1
51     17       12  DM  TEG 12      2
82     17       12  JP  TEG 13      3
46     17       12  GW  TEG 12      1
91     25       13  JB  TEG 14      1
106    25       13  JB  TEG 14      4
71     25       13  JB  TEG 13      1
30     25       13  DM  TEG 11      2
121    25       13  DM  TEG 15      3
86     25       13  JB  TEG 13      4
123    25       13  JB  TEG 15      3
19     25       13  DM  TEG 10      4
75     33       14  GW  TEG 13      2
177    33       14  DM   TEG 3      3
95     33       14  GW  TEG 14      2
305    33       14  JP   TEG 9      2
302    33       14  DM   TEG 9      2
257    33       14  JB   TEG 7      2
8      33       14  GW  TEG 10      2
278    33       14  DM   TEG 8      2
296    41       15  DM   TEG 9      1
21     41       15  JB  TEG 10      4
14     41       15  GW  TEG 10      3
100    41       15  GW  TEG 14      3
80     41       15  GW  TEG 13      3
144    41       15  GW  TEG 16      3
53     47       16  JB  TEG 12      2
76     47       16  JB  TEG 13      2
52     47       16  GW  TEG 12      2
314    47       16  DM   TEG 9      4
96     47       16  JB  TEG 14      2
116    47       16  GW  TEG 15      2
248    47       16  DM   TEG 7      1
290    54       17  DM   TEG 8      4
74     54       17  DM  TEG 13      2
167    54       17  DM   TEG 3      1
105    54       17  GW  TEG 14      4
85     54       17  GW  TEG 13      4
103    54       17  AB  TEG 14      4
317    54       17  JP   TEG 9      4
94     54       17  DM  TEG 14      2
234    54       17  HM   TEG 6      2
232    54       17  DM   TEG 6      2
197    54       17  DM   TEG 4      3
83     54       17  AB  TEG 13      4
227    54       17  DM   TEG 6      1
110    54       17  GW  TEG 15      1
65     54       17  JB  TEG 12      4
18     54       17  AB  TEG 10      4
224    54       17  HM   TEG 5      4
45     54       17  DM  TEG 12      1
298    54       17  JB   TEG 9      1
181    73       18  SN   TEG 3      3
225    73       18  JB   TEG 5      4
260    73       18  DM   TEG 7      3
287    73       18  JB   TEG 8      3
162    73       18  DM   TEG 2      3
59     73       18  JB  TEG 12      3
230    73       18  JB   TEG 6      1
27     73       18  JB  TEG 11      1
3      73       18  JB  TEG 10      1
174    73       18  HM   TEG 3      2
42     83       19  JB  TEG 11      4
40     83       19  DM  TEG 11      4
170    83       19  JB   TEG 3      1
281    83       19  JB   TEG 8      2
202    83       19  DM   TEG 4      4
304    83       19  JB   TEG 9      2
316    83       19  JB   TEG 9      4
272    90       20  DM   TEG 8      1
25     90       20  DM  TEG 11      1
269    90       20  JB   TEG 7      4
125    90       20  SN  TEG 15      3
29     90       20  AB  TEG 11      2
128    90       20  GW  TEG 15      4
267    90       20  GW   TEG 7      4
104    90       20  DM  TEG 14      4
194    90       20  HM   TEG 4      2
31     90       20  GW  TEG 11      2
134    90       20  GW  TEG 16      1
219    90       20  HM   TEG 5      3
64     90       20  GW  TEG 12      4
63     90       20  DM  TEG 12      4
164    90       20  HM   TEG 2      3
210    90       20  JB   TEG 5      1
15     90       20  JB  TEG 10      3
252    90       20  SN   TEG 7      1
152    90       20  DM   TEG 2      1
182    90       20  DM   TEG 3      4
228    90       20  GW   TEG 6      1
84     90       20  DM  TEG 13      4
176   112       21  SN   TEG 3      2
180   112       21  JB   TEG 3      3
275   112       21  JB   TEG 8      1
166   112       21  SN   TEG 2      3
235   112       21  JB   TEG 6      2
236   112       21  SN   TEG 6      2
172   112       21  DM   TEG 3      2
55    112       21  SN  TEG 12      2
35    112       21  DM  TEG 11      3
79    112       21  DM  TEG 13      3
37    112       21  JB  TEG 11      3
62    112       21  AB  TEG 12      4
99    112       21  DM  TEG 14      3
200   112       21  JB   TEG 4      3
139   126       22  GW  TEG 16      2
241   126       22  SN   TEG 6      3
310   126       22  JB   TEG 9      3
115   126       22  DM  TEG 15      2
90    126       22  GW  TEG 14      1
89    126       22  DM  TEG 14      1
291   126       22  GW   TEG 8      4
171   126       22  SN   TEG 3      1
215   126       22  JB   TEG 5      2
57    126       22  DM  TEG 12      3
12    126       22  AB  TEG 10      3
20    126       22  GW  TEG 10      4
138   126       22  DM  TEG 16      2
222   126       22  DM   TEG 5      4
192   126       22  DM   TEG 4      2
242   126       22  DM   TEG 6      4
308   126       22  DM   TEG 9      3
70    126       22  GW  TEG 13      1
69    126       22  DM  TEG 13      1
206   126       22  SN   TEG 4      4
6     146       23  AB  TEG 10      2
13    146       23  DM  TEG 10      3
187   146       23  DM   TEG 4      1
36    146       23  GW  TEG 11      3
151   146       23  SN  TEG 16      4
129   146       23  JB  TEG 15      4
201   146       23  SN   TEG 4      3
268   146       23  HM   TEG 7      4
186   146       23  SN   TEG 3      4
60    146       23  JP  TEG 12      3
135   146       23  JB  TEG 16      1
240   146       23  JB   TEG 6      3
140   146       23  JB  TEG 16      2
209   146       23  HM   TEG 5      1
294   160       24  SN   TEG 8      4
279   160       24  GW   TEG 8      2
50    160       24  AB  TEG 12      2
54    160       24  JP  TEG 12      2
150   160       24  JB  TEG 16      4
286   160       24  HM   TEG 8      3
262   160       24  HM   TEG 7      3
184   160       24  HM   TEG 3      4
226   160       24  SN   TEG 5      4
48    160       24  JP  TEG 12      1
220   160       24  JB   TEG 5      3
34    160       24  AB  TEG 11      3
204   160       24  HM   TEG 4      4
67    160       24  SN  TEG 12      4
318   174       25  SN   TEG 9      4
118   174       25  JP  TEG 15      2
87    174       25  JP  TEG 13      4
107   174       25  JP  TEG 14      4
109   174       25  DM  TEG 15      1
309   174       25  GW   TEG 9      3
38    174       25  JP  TEG 11      3
10    174       25  JP  TEG 10      2
293   174       25  JB   TEG 8      4
66    174       25  JP  TEG 12      4
133   174       25  DM  TEG 16      1
145   174       25  JB  TEG 16      3
2     174       25  GW  TEG 10      1
249   174       25  GW   TEG 7      1
263   188       26  JB   TEG 7      3
211   188       26  SN   TEG 5      1
146   188       26  SN  TEG 16      3
273   188       26  GW   TEG 8      1
179   188       26  HM   TEG 3      3
190   188       26  JB   TEG 4      1
178   188       26  GW   TEG 3      3
312   188       26  SN   TEG 9      3
231   188       26  SN   TEG 6      1
175   188       26  JB   TEG 3      2
143   188       26  DM  TEG 16      3
284   188       26  DM   TEG 8      3
282   200       27  SN   TEG 8      2
213   200       27  GW   TEG 5      2
313   200       27  AB   TEG 9      4
217   200       27  DM   TEG 5      3
315   200       27  GW   TEG 9      4
23    200       27  SN  TEG 10      4
41    200       27  GW  TEG 11      4
221   200       27  SN   TEG 5      3
301   200       27  AB   TEG 9      2
73    200       27  AB  TEG 13      2
93    200       27  AB  TEG 14      2
245   200       27  JB   TEG 6      4
196   200       27  SN   TEG 4      2
111   200       27  JB  TEG 15      1
112   200       27  JP  TEG 15      1
124   200       27  JP  TEG 15      3
264   200       27  SN   TEG 7      3
161   200       27  SN   TEG 2      2
43    200       27  JP  TEG 11      4
303   219       28  GW   TEG 9      2
299   219       28  JP   TEG 9      1
261   219       28  GW   TEG 7      3
246   219       28  SN   TEG 6      4
0     219       28  AB  TEG 10      1
191   219       28  SN   TEG 4      1
131   219       28  SN  TEG 15      4
136   219       28  SN  TEG 16      1
185   219       28  JB   TEG 3      4
58    219       28  GW  TEG 12      3
24    219       28  AB  TEG 11      1
157   219       28  DM   TEG 2      2
169   219       28  HM   TEG 3      1
78    232       29  AB  TEG 13      3
56    232       29  AB  TEG 12      3
237   232       29  DM   TEG 6      3
160   232       29  JB   TEG 2      2
98    232       29  AB  TEG 14      3
26    232       29  GW  TEG 11      1
229   232       29  HM   TEG 6      1
156   232       29  SN   TEG 2      1
311   232       29  JP   TEG 9      3
17    232       29  SN  TEG 10      3
274   232       29  HM   TEG 8      1
117   232       29  JB  TEG 15      2
253   244       30  AB   TEG 7      2
280   244       30  HM   TEG 8      2
108   244       30  AB  TEG 15      1
61    244       30  SN  TEG 12      3
141   244       30  SN  TEG 16      2
68    244       30  AB  TEG 13      1
44    244       30  AB  TEG 12      1
307   244       30  AB   TEG 9      3
214   244       30  HM   TEG 5      2
88    244       30  AB  TEG 14      1
173   254       31  GW   TEG 3      2
33    254       31  JP  TEG 11      2
199   254       31  HM   TEG 4      3
255   254       31  GW   TEG 7      2
4     254       31  JP  TEG 10      1
159   254       31  HM   TEG 2      2
306   260       32  SN   TEG 9      2
218   260       32  GW   TEG 5      3
223   260       32  GW   TEG 5      4
126   260       32  AB  TEG 15      4
189   260       32  HM   TEG 4      1
233   260       32  GW   TEG 6      2
155   260       32  JB   TEG 2      1
205   267       33  JB   TEG 4      4
97    267       33  JP  TEG 14      2
77    267       33  JP  TEG 13      2
11    267       33  SN  TEG 10      2
289   267       33  AB   TEG 8      4
49    267       33  SN  TEG 12      1
127   267       33  DM  TEG 15      4
195   267       33  JB   TEG 4      2
120   275       34  AB  TEG 15      3
137   275       34  AB  TEG 16      2
39    275       34  AB  TEG 11      4
277   275       34  AB   TEG 8      2
163   275       34  GW   TEG 2      3
130   275       34  JP  TEG 15      4
142   275       34  AB  TEG 16      3
193   282       35  GW   TEG 4      2
238   282       35  GW   TEG 6      3
297   282       35  GW   TEG 9      1
183   282       35  GW   TEG 3      4
208   282       35  GW   TEG 5      1
168   282       35  GW   TEG 3      1
244   282       35  HM   TEG 6      4
285   282       35  GW   TEG 8      3
259   290       36  AB   TEG 7      3
5     290       36  SN  TEG 10      1
72    290       36  JP  TEG 13      1
265   290       36  AB   TEG 7      4
16    290       36  JP  TEG 10      3
165   290       36  JB   TEG 2      3
92    290       36  JP  TEG 14      1
188   290       36  GW   TEG 4      1
158   298       37  GW   TEG 2      2
247   298       37  AB   TEG 7      1
113   298       37  SN  TEG 15      1
239   298       37  HM   TEG 6      3
198   302       38  GW   TEG 4      3
147   302       38  AB  TEG 16      4
114   302       38  AB  TEG 15      2
28    305       40  JP  TEG 11      1
153   305       40  GW   TEG 2      1
22    305       40  JP  TEG 10      4
292   305       40  HM   TEG 8      4
283   305       40  AB   TEG 8      3
271   310       41  AB   TEG 8      1
243   310       41  GW   TEG 6      4
300   312       42  SN   TEG 9      1
154   312       42  HM   TEG 2      1
119   314       43  SN  TEG 15      2
203   314       43  GW   TEG 4      4
295   314       43  AB   TEG 9      1
276   314       43  SN   TEG 8      1
288   314       43  SN   TEG 8      3
132   319       44  AB  TEG 16      1

In [70]:
from functools import reduce


## CREATING ROUND BESTS AND WORSTS

round_data = df.groupby(['Pl', 'Round', 'TEG'], as_index=False)[['Sc', 'Stableford', 'GrossVP', 'NetVP']].sum()
# print(round_data)

##BEST GROSS ROUND DETAILS FOR EACH PLAYER
idx_gross_min = round_data.groupby('Pl')['Sc'].idxmin()
# Use the index to select the rows with the minimum 'GrossVP' for each player
min_grossvp_details = round_data[['Pl','Round','TEG','Sc']].loc[idx_gross_min].sort_values(by='Sc', ascending=True)

print('\nBEST GROSS ROUND BY PLAYER\n')
print(min_grossvp_details)
print()

##BEST STABLEFORD DETAILS FOR EACH PLAYER
idx_stab_max = round_data.groupby('Pl')['Stableford'].idxmax()
# Use the index to select the rows with the minimum 'GrossVP' for each player
max_stab_details = round_data[['Pl','Round','TEG','Stableford']].loc[idx_stab_max].sort_values(by='Stableford', ascending=False)

print('\nBEST STABLEFORD ROUND BY PLAYER\n')
print(max_stab_details)
print()

## BEST SINGLE ROUND FOR EACH PL (NO DETAILS)
best_gross = round_data.groupby('Pl', as_index=False)['GrossVP'].min()
best_net = round_data.groupby('Pl', as_index=False)['NetVP'].min()
best_stab = round_data.groupby('Pl', as_index=False)['Stableford'].max()
best_score = round_data.groupby('Pl', as_index=False)['Sc'].min()

## COMBINING BEST ROUND DATA INTO ONE TABLE
best_dfs = [best_score,best_gross,best_net,best_stab]
pl_best_rds = reduce(lambda left, right: pd.merge(left, right, on='Pl'), best_dfs)
pl_best_rds.rename(columns={'GrossVP': 'Best gross', 'Stableford': 'Best Stableford', 'NetVP': 'Best Net', 'Sc': 'Best Score'}, inplace=True)

print('\nBEST ROUNDS\n')
print(pl_best_rds)
print()


## WORST SINGLE ROUND FOR EACH PL (NO DETAILS)
worst_gross = round_data.groupby('Pl', as_index=False)['GrossVP'].max()
worst_net = round_data.groupby('Pl', as_index=False)['NetVP'].max()
worst_stab = round_data.groupby('Pl', as_index=False)['Stableford'].min()
worst_score = round_data.groupby('Pl', as_index=False)['Sc'].max()

## COMBINING BEST ROUND DATA INTO ONE TABLE
worst_dfs = [worst_score,worst_gross,worst_net,worst_stab]
pl_worst_rds = reduce(lambda left, right: pd.merge(left, right, on='Pl'), worst_dfs)
pl_worst_rds.rename(columns={'GrossVP': 'Worst gross', 'Stableford': 'Worst Stableford', 'NetVP': 'Worst Net', 'Sc': 'Worst Score'}, inplace=True)

print('\nWORST ROUNDS\n')
print(pl_worst_rds)
print()

BEST GROSS ROUND BY PLAYER

     Pl  Round     TEG  Sc
40   DM      1  TEG 10  75
218  JB      3  TEG 13  79
150  GW      4  TEG 16  80
170  HM      2   TEG 7  82
291  SN      2   TEG 5  82
261  JP      3  TEG 13  83
30   AB      4  TEG 10  88


BEST STABLEFORD ROUND BY PLAYER

     Pl  Round     TEG  Stableford
30   AB      4  TEG 10          51
170  HM      2   TEG 7          51
40   DM      1  TEG 10          49
257  JP      2   TEG 9          49
293  SN      2   TEG 7          49
110  GW      1   TEG 6          48
197  JB      1   TEG 7          47


BEST ROUNDS

   Pl  Best Score  Best gross  Best Net  Best Stableford
0  AB          88          17       -15               51
1  DM          75           4       -13               49
2  GW          80          10       -12               48
3  HM          82          10       -15               51
4  JB          79           8       -10               47
5  JP          83          12       -13               49
6  SN          82          10       -13               49


WORST ROUNDS

   Pl  Worst Score  Worst gross  Worst Net  Worst Stableford
0  AB          115           44         14                27
1  DM          104           33         16                22
2  GW          115           43         15                23
3  HM          113           42         24                18
4  JB          107           36         13                28
5  JP          112           40         19                21
6  SN          115           43         25                17

In [71]:
## CREATING TEG BESTS AND WORSTS

## EXCLUDE TEG 2 DUE TO FEWER ROUNDS

df_ex2 = df[df['TEG'] != 'TEG 2']

teg_data = df_ex2.groupby(['Pl', 'TEG'], as_index=False)[['Sc', 'Stableford', 'GrossVP', 'NetVP']].sum()
# print(round_data)



## BEST TEG FOR EACH PL (NO DETAILS)
best_gross_teg = teg_data.groupby('Pl', as_index=False)['GrossVP'].min()
best_net_teg = teg_data.groupby('Pl', as_index=False)['NetVP'].min()
best_stab_teg = teg_data.groupby('Pl', as_index=False)['Stableford'].max()
best_score_teg = teg_data.groupby('Pl', as_index=False)['Sc'].min()

## COMBINING BEST ROUND DATA INTO ONE TABLE
best_dfs_teg = [best_score_teg,best_gross_teg,best_net_teg,best_stab_teg]
pl_best_tegs = reduce(lambda left, right: pd.merge(left, right, on='Pl'), best_dfs_teg)
pl_best_tegs.rename(columns={'GrossVP': 'Best gross', 'Stableford': 'Best Stableford', 'NetVP': 'Best Net', 'Sc': 'Best Score'}, inplace=True)

print('\nBEST TEGS\n')
print(pl_best_tegs)
print()


## WORST SINGLE ROUND FOR EACH PL (NO DETAILS)
worst_gross_teg = teg_data.groupby('Pl', as_index=False)['GrossVP'].max()
worst_net_teg = teg_data.groupby('Pl', as_index=False)['NetVP'].max()
worst_stab_teg = teg_data.groupby('Pl', as_index=False)['Stableford'].min()
worst_score_teg = teg_data.groupby('Pl', as_index=False)['Sc'].max()

## COMBINING BEST ROUND DATA INTO ONE TABLE
worst_dfs_teg = [worst_score_teg,worst_gross_teg,worst_net_teg,worst_stab_teg]
pl_worst_tegs = reduce(lambda left, right: pd.merge(left, right, on='Pl'), worst_dfs_teg)
pl_worst_tegs.rename(columns={'GrossVP': 'Worst gross', 'Stableford': 'Worst Stableford', 'NetVP': 'Worst Net', 'Sc': 'Worst Score'}, inplace=True)

print('\nWORST TEGS\n')
print(pl_worst_tegs)
print()

BEST TEGS

   Pl  Best Score  Best gross  Best Net  Best Stableford
0  AB         376          90       -38              184
1  DM         337          51       -23              170
2  GW         347          63       -28              173
3  HM         359          69       -31              175
4  JB         337          50       -18              164
5  JP         378          88       -20              172
6  SN         358          68       -24              169


WORST TEGS

   Pl  Worst Score  Worst gross  Worst Net  Worst Stableford
0  AB          433          150         38               114
1  DM          377           93         25               125
2  GW          435          152         40               110
3  HM          408          123         43               111
4  JB          396          113         28               130
5  JP          418          132         48               112
6  SN          422          137         65               100

In [82]:
## TEG 16 SUMMARY

df16 = df[df['TEG'] == 'TEG 16']

pivot16 = df16.pivot_table(index = 'Round', columns = 'Pl', values = ['Sc','GrossVP','NetVP','Stableford'],aggfunc='sum')
# print(pivot16)
# print()

totals16 = pivot16.sum(axis=0).to_frame().T
totals16.index = ['Total']
# print(totals16)

pivot16_totals = pd.concat([pivot16,totals16])
print('\nTEG16 TOTALS\n')
print(pivot16_totals)

TEG16 TOTALS

      GrossVP                  NetVP                 Sc                      \
Pl         AB  DM  GW  JB   SN    AB DM GW  JB  SN   AB   DM   GW   JB   SN
1          42  23  18  21   26    12  3  2   2  -3  113   94   89   92   97
2          34  22  22  23   30     4  2  6   4   1  106   94   94   95  102
3          34  26  15  25   26     4  6 -1   6  -3  106   98   87   97   98
4          38  11  11  24   23     8 -9 -5   5  -6  107   80   80   93   92
Total     148  82  66  93  105    28  2  2  17 -11  432  366  350  377  389

      Stableford
Pl            AB   DM   GW   JB   SN
1             29   33   34   34   39
2             32   34   30   32   35
3             33   30   37   33   39
4             33   45   42   32   43
Total        127  142  143  131  156